# Generated by Django 3.2.12 on 2022-03-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('primary_keys', models.TextField()),
                ('secondary_keys', models.TextField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
